# Generated by Django 5.0 on 2023-12-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoga_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("cid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyClasses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("batch", models.CharField(max_length=20)),
                ("feestatus", models.BooleanField(default=False)),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yoga_api.customer",
                    ),
                ),
            ],
            options={
                "unique_together": {("cid", "month", "year")},
            },
        ),
        migrations.DeleteModel(
            name="EnrolledUser",
        ),
    ]
